apiVersion: v1
kind: Service
metadata:
  name: admin-server
  namespace: spring-petclinic
spec:
  ports:
    - name: admin-server
      port: 9090
      targetPort: 9090
  selector:
    app: petclinic
    tier: admin-server
status:
  loadBalancer: {}
