apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: spring-petclinic
spec:
  ports:
    - name: "config-server"
      port: 8888
      targetPort: 8888
  selector:
    app: petclinic
    tier: config-server
status:
  loadBalancer: {}
