apiVersion: v1
kind: Service
metadata:
  name: customers-service
  namespace: spring-petclinic
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
  selector:
    app: petclinic
    tier: customers-service
status:
  loadBalancer: {}
