apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.29.0 (997957870)
  creationTimestamp: null
  labels:
    io.kompose.service: database
  name: database
  namespace: spring-petclinic
spec:
  ports:
    - name: "mysql"
      port: 3306
      targetPort: 3306
  selector:
    app: petclinic
    tier: database
status:
  loadBalancer: {}
