apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: spring-petclinic
  labels:
    app: petclinic
    io.kompose.service: database-claim0
  name: database-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
