apiVersion: v1
kind: Service
metadata:
  name: discovery-server
  namespace: spring-petclinic
spec:
  ports:
    - name: "8761"
      port: 8761
      targetPort: 8761
  selector:
    app: petclinic
    tier: discovery-server
status:
  loadBalancer: {}
