apiVersion: v1
kind: Service
metadata:
  name: grafana-server
  namespace: spring-petclinic # Ajout du namespace
spec:
  ports:
    - name: "grafana"
      port: 3000
      targetPort: 3000
  selector:
    app: petclinic # Modification du sélecteur pour correspondre au label du déploiement
    tier: grafana-server # Modification du sélecteur pour correspondre au label du déploiement
status:
  loadBalancer: {}
