apiVersion: v1
kind: Service
metadata:
  name: grafana-lb
  namespace: spring-petclinic
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: petclinic
    tier: grafana-server
