# apiVersion: v1
# kind: Service
# metadata:
#   name: prometheus-service
#   namespace: spring-petclinic
# spec:
#   selector:
#     app: petclinic
#     tier: prometheus-server
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 9090
#   type: LoadBalancer
