apiVersion: v1
kind: Service
metadata:
  name: prometheus-server
  namespace: spring-petclinic
spec:
  ports:
    - name: "9090"
      port: 9090
      targetPort: 9090
  selector:
    app: petclinic
    tier: prometheus-server
status:
  loadBalancer: {}
