apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: spring-petclinic
  name: pod-reader
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-pods-global
subjects:
  - kind: ServiceAccount
    name: default
    namespace: spring-petclinic
roleRef:
  kind: ClusterRole
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
