apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: "C:\\ProgramData\\chocolatey\\lib\\kubernetes-kompose\\tools\\kompose.exe convert"
    kompose.version: "1.29.0 (997957870)"
  creationTimestamp: null
  name: vets-service
  namespace: spring-petclinic
spec:
  ports:
    - name: "8083"
      port: 8083
      targetPort: 8083
  selector:
    app: petclinic
    tier: vets-service
status:
  loadBalancer: {}
