name: Deploy to Kubernetes

on:
  workflow_run:
    workflows: ["Docker Build and Push", "Terraform Apply"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true

      - name: Install gcloud components
        run: gcloud components install gke-gcloud-auth-plugin

      - name: Configure Kubernetes context
        run: |
          gcloud container clusters get-credentials app-cluster --zone europe-west1 --project ${{ secrets.GCP_PROJECT_ID }}

      - name: Check if namespace exists
        id: check-namespace
        run: |
          exists=$(kubectl get ns spring-petclinic --ignore-not-found=true -o jsonpath='{.metadata.name}')
          echo "::set-output name=namespace_exists::${exists}"

      - name: Create new namespace
        run: kubectl create ns spring-petclinic
        if: steps.check-namespace.outputs.namespace_exists != 'spring-petclinic'

      - name: Deploy application
        run: kubectl apply -f k8s
