name: Docker Image Sync

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin

      - name: Pull and push Docker images
        run: |
          docker pull springcommunity/spring-petclinic-admin-server
          docker tag springcommunity/spring-petclinic-admin-server usinegk2023/spring-petclinic-admin-server
          docker push usinegk2023/spring-petclinic-admin-server

          docker pull springcommunity/spring-petclinic-api-gateway
          docker tag springcommunity/spring-petclinic-api-gateway usinegk2023/spring-petclinic-api-gateway
          docker push usinegk2023/spring-petclinic-api-gateway

          docker pull springcommunity/spring-petclinic-config-server
          docker tag springcommunity/spring-petclinic-config-server usinegk2023/spring-petclinic-config-server
          docker push usinegk2023/spring-petclinic-config-server

          docker pull springcommunity/spring-petclinic-customers-service
          docker tag springcommunity/spring-petclinic-customers-service usinegk2023/spring-petclinic-customers-service
          docker push usinegk2023/spring-petclinic-customers-service

          docker pull springcommunity/spring-petclinic-discovery-server
          docker tag springcommunity/spring-petclinic-discovery-server usinegk2023/spring-petclinic-discovery-server
          docker push usinegk2023/spring-petclinic-discovery-server

          docker pull springcommunity/spring-petclinic-vets-service
          docker tag springcommunity/spring-petclinic-vets-service usinegk2023/spring-petclinic-vets-service
          docker push usinegk2023/spring-petclinic-vets-service

          docker pull springcommunity/spring-petclinic-visits-service
          docker tag springcommunity/spring-petclinic-visits-service usinegk2023/spring-petclinic-visits-service
          docker push usinegk2023/spring-petclinic-visits-service
